# Generated by Django 4.2.1 on 2023-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=15, verbose_name="Book's name")),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Book picture')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Book's price")),
            ],
        ),
    ]
