# Generated by Django 4.2.1 on 2023-06-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='price',
            new_name='book_price',
        ),
    ]
