# Generated by Django 4.2.1 on 2023-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_alter_author_author_bio'),
        ('books', '0010_remove_books_book_author_books_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.ManyToManyField(to='directories.author'),
        ),
    ]
