# Generated by Django 4.2.1 on 2023-06-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_alter_author_author_bio'),
        ('books', '0012_remove_books_book_author_books_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directories.serie', verbose_name='Serie'),
        ),
    ]
