# Generated by Django 4.2.1 on 2023-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_books_book_genre_books_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Year'),
        ),
    ]
