# Generated by Django 4.2.1 on 2023-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_books_book_cover_books_book_isbn_books_book_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cover'),
        ),
    ]
