# Generated by Django 4.2.1 on 2023-06-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_alter_author_author_bio'),
        ('books', '0017_alter_books_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_age',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Age Restrictions'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directories.publisher', verbose_name='Publisher'),
        ),
    ]
