# Generated by Django 4.2.1 on 2023-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_books_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рейтинг'),
        ),
    ]
