# Generated by Django 4.2.1 on 2023-06-21 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_alter_books_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Book's price"),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_weight',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2023)], verbose_name='Year'),
        ),
    ]
