# Generated by Django 4.2.1 on 2023-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_books_created_at_books_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
