# Generated by Django 4.2.1 on 2023-06-27 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_alter_books_created_at_alter_books_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Book's price"),
        ),
    ]
