# Generated by Django 4.2.1 on 2023-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_alter_books_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Book picture'),
        ),
    ]
