# Generated by Django 4.2.1 on 2023-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_active',
            field=models.CharField(choices=[('Y', 'active'), ('N', 'inactive')], max_length=4, verbose_name='Book active'),
        ),
    ]
