# Generated by Django 4.2.1 on 2023-07-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_alter_books_picture_alter_comments_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.CharField(choices=[('M', 'мягкая'), ('T', 'твердая')], default='M', max_length=5, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=40, verbose_name="Book's name"),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_active',
            field=models.CharField(choices=[('Y', 'активна'), ('N', 'не активна')], max_length=4, verbose_name='Book active'),
        ),
    ]
