# Generated by Django 4.2.1 on 2023-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_alter_books_book_cover_alter_books_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=150),
        ),
    ]
