# Generated by Django 4.2.1 on 2023-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_author_series_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author2_name',
        ),
        migrations.RemoveField(
            model_name='series',
            name='series_name',
        ),
        migrations.AddField(
            model_name='series',
            name='serie_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Serie'),
        ),
    ]
