# Generated by Django 4.2.1 on 2023-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_remove_author_author2_name_remove_series_series_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.AddField(
            model_name='author',
            name='author_firstname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='author',
            name='author_lastname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Author Lastname'),
        ),
        migrations.AlterField(
            model_name='series',
            name='serie_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Serie'),
        ),
    ]
