# Generated by Django 4.2.1 on 2023-05-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_remove_author_author_name_author_author_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Genre')),
            ],
        ),
    ]
