# Generated by Django 4.2.1 on 2023-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Genre description'),
        ),
    ]
