# Generated by Django 4.2.1 on 2023-05-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0006_genre_genre_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Genre description'),
        ),
    ]
