# Generated by Django 4.2.1 on 2023-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_rename_series_serie_alter_genre_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='serie_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Serie description'),
        ),
    ]
