# Generated by Django 4.2.1 on 2023-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0008_serie_serie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=30, verbose_name='Publisher')),
                ('publisher_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Publisher description')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='author_firstname',
            field=models.CharField(max_length=15, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_lastname',
            field=models.CharField(max_length=15, verbose_name='Author Lastname'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=30, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='serie_name',
            field=models.CharField(max_length=40, verbose_name='Serie'),
        ),
    ]
