# Generated by Django 4.2.1 on 2023-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0011_alter_author_author_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='-', upload_to='uploads/%Y/%m/%d/', verbose_name='Author picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='author_firstname',
            field=models.CharField(default="Author's firstname", help_text="Add Author's name, max len = 15", max_length=15, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_lastname',
            field=models.CharField(default="Author's lastname", help_text="Add Author's lastname, max len = 15", max_length=15, verbose_name='Author Lastname'),
        ),
    ]
