# Generated by Django 4.2.1 on 2023-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0012_author_picture_alter_author_author_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_bio',
            field=models.CharField(blank=True, help_text="Author's biography, max len = 300", max_length=300, null=True, verbose_name='Author Bio'),
        ),
    ]
