# Generated by Django 4.2.1 on 2023-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0013_author_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_bio',
            field=models.TextField(blank=True, help_text="Author's biography, max len = 300", max_length=255, null=True, verbose_name='Author Bio'),
        ),
    ]
