# Generated by Django 4.2.1 on 2023-07-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0015_alter_author_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_bio',
            field=models.TextField(blank=True, help_text="Author's biography, max len = 1000", max_length=1000, null=True, verbose_name='Author Bio'),
        ),
    ]
