# Generated by Django 4.2.1 on 2023-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0016_alter_author_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='picture',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='Author picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='picture',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='Author picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='picture',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='Author picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='author_bio',
            field=models.TextField(blank=True, help_text="Author's biography, max len = 1000", null=True, verbose_name='Author Bio'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, null=True, verbose_name='Genre description'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_description',
            field=models.TextField(blank=True, null=True, verbose_name='Publisher description'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='serie_description',
            field=models.TextField(blank=True, null=True, verbose_name='Serie description'),
        ),
    ]
