# Generated by Django 4.2.1 on 2023-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_goodincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_adress', models.TextField(verbose_name='Delivery adress')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('Oformlen', 'Oformlen'), ('At_work', 'At_work'), ('Vydan', 'Vydan'), ('Closed', 'Closed')], default='NEW', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
