# Generated by Django 4.2.1 on 2023-07-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_books_picture'),
        ('orders', '0004_alter_order_cart_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_adress',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=' ', verbose_name='Delivery address'),
        ),
        migrations.AlterField(
            model_name='goodincart',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books', verbose_name='books'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('Oformlen', 'Оформлен'), ('At_work', 'В работе'), ('Vydan', 'Выдан'), ('Closed', 'Закрыт')], default='NEW', max_length=8, verbose_name='Order status'),
        ),
    ]
