# Generated by Django 4.2.1 on 2023-07-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_books_picture'),
        ('orders', '0005_remove_order_delivery_adress_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodincart',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='Enter your adress', verbose_name='Delivery address'),
        ),
    ]
