# Generated by Django 4.2.1 on 2023-07-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_goodincart_good_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('OFORMLEN', 'Оформлен'), ('ATWORK', 'В работе'), ('VYDAN', 'Выдан'), ('CLOSED', 'Закрыт')], default=('NEW', 'Новый'), max_length=8, verbose_name='Order status'),
        ),
    ]
