# Generated by Django 4.2.1 on 2023-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('OFORMLEN', 'Оформлен'), ('ATWORK', 'В работе'), ('VYDAN', 'Выдан'), ('CLOSED', 'Закрыт')], default='NEW', max_length=8, verbose_name='Order status'),
        ),
    ]
