# Generated by Django 4.2.1 on 2023-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Enter your Phone', max_length=10, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('OFORMLEN', 'Оформлен'), ('ATWORK', 'В работе'), ('VYDAN', 'Выдан'), ('CLOSED', 'Закрыт')], default=('NEW', 'Новый'), max_length=8, verbose_name='Order status'),
        ),
    ]
