# Generated by Django 4.2.1 on 2023-07-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0002_rename_date_of_birth_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
