# Generated by Django 4.2.1 on 2023-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_profile_options_remove_profile_address1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+37500123456', max_length=12, verbose_name='Телефон'),
        ),
    ]
