# Generated by Django 4.2.1 on 2023-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_profile_options_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='profile',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.TextField(blank=True, max_length=500, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон'),
        ),
    ]
