# Generated by Django 4.2.1 on 2023-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_profile_bio_profile_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=14, verbose_name='Телефон'),
        ),
    ]
